default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: db
  username: postgres
  password: postgres

development:
  <<: *default
  database: hero_development

test:
  <<: *default
  database: hero_test
