require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/castles", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Castle. As you add validations to Castle, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Castle.create! valid_attributes
      get castles_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      castle = Castle.create! valid_attributes
      get castle_url(castle)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_castle_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      castle = Castle.create! valid_attributes
      get edit_castle_url(castle)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Castle" do
        expect {
          post castles_url, params: { castle: valid_attributes }
        }.to change(Castle, :count).by(1)
      end

      it "redirects to the created castle" do
        post castles_url, params: { castle: valid_attributes }
        expect(response).to redirect_to(castle_url(Castle.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Castle" do
        expect {
          post castles_url, params: { castle: invalid_attributes }
        }.to change(Castle, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post castles_url, params: { castle: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested castle" do
        castle = Castle.create! valid_attributes
        patch castle_url(castle), params: { castle: new_attributes }
        castle.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the castle" do
        castle = Castle.create! valid_attributes
        patch castle_url(castle), params: { castle: new_attributes }
        castle.reload
        expect(response).to redirect_to(castle_url(castle))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        castle = Castle.create! valid_attributes
        patch castle_url(castle), params: { castle: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested castle" do
      castle = Castle.create! valid_attributes
      expect {
        delete castle_url(castle)
      }.to change(Castle, :count).by(-1)
    end

    it "redirects to the castles list" do
      castle = Castle.create! valid_attributes
      delete castle_url(castle)
      expect(response).to redirect_to(castles_url)
    end
  end
end
